AWSTemplateFormatVersion: "2010-09-09"
Description: "Infrastructure all of storage"

Parameters:
  ImageTableName:
    Type: "String"
    Default: "simpleapp-me"
  RepositoryName:
    Type: "String"
    Default: "simpleapp-me"
  AvatarTempObjectPrefix:
    Type: "String"
    Default: "tmp/user-avatar/"

Resources:

  SimpleAppUploadedUserAvatarQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 450

  SimpleAppUploadedUserAvatarQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "s3.amazonaws.com"
            Action:
              - "SQS:SendMessage"
            Resource: !GetAtt SimpleAppUploadedUserAvatarQueue.Arn
      Queues:
        - !Ref SimpleAppUploadedUserAvatarQueue

  SimpleAppPublicContentBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      AccessControl: "Private"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: "Enabled"
      NotificationConfiguration:
        QueueConfigurations:
          - Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: "prefix"
                    Value: !Ref AvatarTempObjectPrefix
                  - Name: "suffix"
                    Value: ".png"
            Queue: !GetAtt SimpleAppUploadedUserAvatarQueue.Arn
          - Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: "prefix"
                    Value: !Ref AvatarTempObjectPrefix
                  - Name: "suffix"
                    Value: ".webp"
            Queue: !GetAtt SimpleAppUploadedUserAvatarQueue.Arn
          - Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: "prefix"
                    Value: !Ref AvatarTempObjectPrefix
                  - Name: "suffix"
                    Value: ".jpeg"
            Queue: !GetAtt SimpleAppUploadedUserAvatarQueue.Arn
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 2
            Prefix: AvatarTempObjectPrefix
            Status: "Enabled"

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  SimpleAppMeTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref ImageTableName
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      StreamSpecification:
        StreamViewType: "NEW_AND_OLD_IMAGES"

  SimpleAppMeRepository:
    Type: "AWS::ECR::Repository"
    DeletionPolicy: "Delete"
    Properties:
      ImageTagMutability: "MUTABLE"
      RepositoryName: !Ref RepositoryName

Outputs:

  BucketName:
    Value: !Ref SimpleAppPublicContentBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"

  BucketDomainName:
    Value: !GetAtt SimpleAppPublicContentBucket.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-BucketDomainName"

  BucketUrl:
    Value:
      Fn::Join:
        - ""
        - - "https://"
          - !GetAtt SimpleAppPublicContentBucket.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-BucketUrl"

  SimpleAppMeTableArn:
    Value: !GetAtt SimpleAppMeTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SimpleAppMeTableArn"

  SimpleAppMeTableName:
    Value: !Ref SimpleAppMeTable
    Export:
      Name: !Sub "${AWS::StackName}-SimpleAppMeTableName"

  SimpleAppMeTableStreamArn:
    Value: !GetAtt SimpleAppMeTable.StreamArn
    Export:
      Name: !Sub "${AWS::StackName}-SimpleAppMeTableStreamArn"

  SimpleAppMeRepositoryName:
    Value: !Ref SimpleAppMeRepository
    Export:
      Name: !Sub "${AWS::StackName}-SimpleAppMeRepositoryName"

  SimpleAppUploadedUserAvatarQueueUrl:
    Value: !Ref SimpleAppUploadedUserAvatarQueue
    Export:
      Name: !Sub "${AWS::StackName}-SimpleAppUploadedUserAvatarQueueUrl"

  SimpleAppUploadedUserAvatarQueueArn:
    Value: !GetAtt SimpleAppUploadedUserAvatarQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SimpleAppUploadedUserAvatarQueueArn"

  SimpleAppUploadedUserAvatarQueueName:
    Value: !GetAtt SimpleAppUploadedUserAvatarQueue.QueueName
    Export:
      Name: !Sub "${AWS::StackName}-SimpleAppUploadedUserAvatarQueueName"
